Update action.yml

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -30,49 +30,23 @@ outputs:
 runs:
   using: 'composite'
   steps:
-    - name: Checkout code
-      uses: actions/checkout@v2
-
-    - name: Setup PHP
-      uses: shivammathur/setup-php@v2
-      with:
-        php-version: ${{ inputs.php-version }}
-        tools: composer, php-cs-fixer
-
-    - name: Install dependencies
-      shell: bash
-      run: composer install --no-dev --prefer-dist --optimize-autoloader
-
-    - name: Prepare environment
-      shell: bash
+    - name: Set up job
       run: |
-        cp .env.example .env
-        php artisan key:generate
-        cp .env.example .env
-        php artisan key:generate
-
-    - name: Set permissions
-      shell: bash
-      run: |
-        sudo chown -R $USER:www-data storage bootstrap/cache
-        sudo chmod -R 775 storage bootstrap/cache
-    - name: Deploy to VPS
-      uses: appleboy/ssh-action@master
-      with:
-        host: ${{ inputs.vps-host }}
-        username: ${{ inputs.vps-username }}
-        key: ${{ inputs.vps-private-key }}
-        script: |
-          cd ${{ inputs.deploy-path }}
-          sudo chown -R $USER:www-data storage/ bootstrap/cache public/
-          sudo chmod -R 775 storage bootstrap/cache public/
-          git reset --hard
-          git clean -fd
-          git pull origin ${{ inputs.production-branch }}
-          /usr/bin/php${{ inputs.php-version }} $(which composer) install --no-dev --prefer-dist --optimize-autoloader
-          /usr/bin/php${{ inputs.php-version }} artisan optimize
-          /usr/bin/php${{ inputs.php-version }} artisan optimize:clear
-          /usr/bin/php${{ inputs.php-version }} artisan storage:link
+        case ${{ inputs.job }} in
+          ci)
+            ./entrypoint.sh ci
+            ;;
+          code_cleanup)
+            ./entrypoint.sh code_cleanup
+            ;;
+          cd)
+            ./entrypoint.sh cd
+            ;;
+          *)
+            echo "Invalid job"
+            exit 1
+            ;;
+        esac
 branding:
   icon: 'wind'
   color: 'blue'
